### PR TITLE
Update tests to not allow hack shortcut

### PR DESCRIPTION
**Pull request by toy**
Otherwise `drop dup` is the simplest way to pass the tests

### CODE REVIEW

**Review by keiravillekode — COMMENTED** [review]
(I am not an 8th maintainer.)

lgtm

**Comment by glennj** [comment]
It looks like these exercises do the same thing. Care to include them in your PR?

* acronym
* darts
* etl
* pythagorean-triplet
* sieve

**Comment by toy** [comment]
@glennj Done, also yacht and hello-world (just for consistency)

**Comment by glennj** [comment]
I'm seeing this error for pythagorean-triplet
```
PANIC: expected stack depth to be 3
Stack is:
Stack depth: 2
 0 a: 0000000110ae0f80 1  [[3,4,5]]
 1 s: 000000011104fee0 1  triplets whose sum is 12

7 tests planned - 0 passed - 0 skipped - 0 failed
... FAIL - not all tests completed
pythagorean-triplet tests exited with 255
```
Please look into that.

**Comment by toy** [comment]
@glennj Forgot to comment to ping: I missed the difference in pythagorean-triplet test, so I changed how it works

**Comment by glennj** [comment]
Can you verify it's running for you? I get this:
```
$ 8th -v
8th 24.07 MACOS64 Free (a1df7b96/2024-10-22) custid: 44e5dc98

$ bin/test-no-docker -r pythagorean-triplet
triplets whose sum is 12  ... OK
triplets whose sum is 108  ... OK
triplets whose sum is 1000  ... OK
no matching triplets for 1001  ... OK
returns all matching triplets  ... OK
several matching triplets  ... OK
7 tests planned - 6 passed - 0 skipped - 0 failed
... FAIL - not all tests completed
... FAIL - not all tests completed
7 tests planned - 6 passed - 0 skipped - 0 failed
Exception: bad memory access or corruption 0000000b 000000010ad6cfa5: at line 66 byte 1666 in /private/var/folders/g0/shf2zm4x0l5gwq3cc4s5zmth0000gn/T/tmp.g0DMdZoQLb/test.8th <- ns:db: task REPL
```

**Comment by toy** [comment]
I get this also on main, so the error comes from the example solution

**Comment by toy** [comment]
Had to solve the exercise and if I replace `exercises/practice/pythagorean-triplet/.meta/example.8th` with my solution then `bin/test-no-docker -r pythagorean-triplet ` succeeds. Trying to check the place of the error suggests that the problem is in 8th itself, as the crash happens when calling `n:gcd` with `1` and `3` as top values on stack.

**Comment by keiravillekode** [comment]
Perhaps `pythagorean-triplet` should be omitted from this PR.

**Comment by toy** [comment]
@keiravillekode I think it would be better to resolve the issue with pythagorean-triplet example solution then rebase this, otherwise this PR would be incomplete in the goal

**Comment by glennj** [comment]
>  I think it would be better to resolve the issue with pythagorean-triplet example solution then rebase this, otherwise this PR would be incomplete in the goal

That sounds like a good plan. Can you make it so?

**Comment by toy** [comment]
Do you mean fixing the problem in example solution, or just replacing it by a working one?

**Comment by glennj** [comment]
Replace it.

**Comment by toy** [comment]
@glennj https://github.com/exercism/8th/pull/205

**Comment by glennj** [comment]
@toy, 205 is merged.

**Comment by toy** [comment]
@glennj Rebased, now `bin/test-no-docker -a` and `bin/test-no-docker -r pythagorean-triplet` run successfully

**Comment by glennj** [comment]
> now `bin/test-no-docker -a` and `bin/test-no-docker -r pythagorean-triplet` run successfully

Take care when testing all exercises to use `-r` to run all the skipped tests -- that's usually where the bugs are uncovered.

However I cloned your repo and all the tests pass. Thanks for all the work to see this PR through.

**Review by glennj — APPROVED** [review]

**Pull request merged**
