### PR TITLE
needs utils/latebind

### PR DESCRIPTION
**Pull request by axtens**

### CODE REVIEW

**Comment by axtens** [comment]
the earlier PR can be trashed. And "[no important files changed]" needs to be asserted

**Review by glennj — APPROVED** [review]

**Comment by glennj** [comment]
The Test check failed. Does this change actually fix the problem?

**Comment by axtens** [comment]
Doesn't the Test/ci always fail? (Because of the `Input required and not supplied: token`) @ErikSchierboom ?

**Comment by glennj** [comment]
Yes, but I'm asking if this fixes the issue you reported in https://forum.exercism.org/t/cli-debugging-of-matching-brackets-throws-error-in-test-library/11530

**Comment by glennj** [comment]
> If this PR does not affect the result of the test (or, for example, adds an edge case that is not worth rerunning all tests for), please add the following to the merge-commit message which will stops student's tests from re-running. Please copy-paste to avoid typos.
>
> [no important files changed]

@ErikSchierboom a question: the test file is listed as an invalidator for each exercise. Which takes precedence, "no important files changed" or invalidators?

**Comment by ErikSchierboom** [comment]
No important files changed

**Comment by ErikSchierboom** [comment]
> Doesn't the Test/ci always fail? (Because of the Input required and not supplied: token) @ErikSchierboom ?

Well, only when the PR is submitted from a fork. I therefore highly recommend not using a fork for PRs but to push branches directly to this repo and then PR from there.

**Comment by glennj** [comment]
> Yes, but I'm asking if this fixes the issue you reported in https://forum.exercism.org/t/cli-debugging-of-matching-brackets-throws-error-in-test-library/11530

@axtens does it?

**Comment by axtens** [comment]
@glennj No, it does not fix the problem. In `circular-buffer` I still get 
```
$ bin/test-no-docker circular-buffer
Exception: Unknown l:: at line 68 byte 1615 in libs/exercism/test <- G:eval <- I:include?: task REPL
```
and that is AFTER having updated libs/exercism/test to include `needs utils/latebind ` on line 2.

I shall take this up with Ron.

**Comment by axtens** [comment]
And `diff exercises/practice/bob/libs/exercism/test exercises/practice/circular-buffer/libs/exercism/test` shows no differences.  bob's tests run flawlessly.

**Comment by axtens** [comment]
Got a reply from Ron <https://8th-dev.com/forum/index.php?topic=2864.0;topicseen> will fix tonight

**Comment by axtens** [comment]
Actually it might not be so easy as that's a change to a system library not one of ours.

**Comment by axtens** [comment]
@ErikSchierboom , how hard/easy would it be to edit a system library file in the 8th installation? We are due an update of the binary so I could make the change before I submit the zip file to you.

**Comment by axtens** [comment]
I've sent @ErikSchierboom the latest version of the interpreter with an updated latebind. Once that's in place I'll double-check the repo's tests.

**Comment by ErikSchierboom** [comment]
@axtens The structure of the zip file is different from normal. I think you added a top directory that wasn't there. Could you fix?

**Comment by axtens** [comment]
Righto

**Pull request closed without merging**
