### PR TITLE
Testfix

### PR DESCRIPTION
**Pull request by axtens**
PR'ed not from fork.

### CODE REVIEW

**Comment by axtens** [comment]
Woo hoo! All checks passed!!

**Review by ErikSchierboom — APPROVED** [review]
Lovely!

**Review by glennj — APPROVED** [review]

**Comment by glennj** [comment]
@ErikSchierboom this PR will re-test everything in the track. Is this a case for `[no important files changed]` even though important files are changed?

**Comment by ErikSchierboom** [comment]
I think so, as it shouldn't really influence the test results, right?

**Comment by glennj** [comment]
@axtens Thanks for following up with this.

**Comment by axtens** [comment]
It had to be done. It was a "call of duty" thing. It wasn't unpleasant. Fiddly.

**Pull request merged**
