### PR TITLE
Exit status for tests should be non-zero if test failures

### PR DESCRIPTION
**Pull request by glennj**
Or if not all tests run.

This also adds a test summary:
```none
X tests planned - Y passed - Z failed
```

### CODE REVIEW

**Comment by axtens** [comment]
Hello @softmoth , please add your "two bob" on this.

**Comment by glennj** [comment]
This sets the exit status to the number of test failures, or if not all tests were executed the exit status is -1. 

Looking closer at [the test runner](https://github.com/exercism/8th-test-runner/blob/111f0475550c0329355dfe1bb1e44ed104cd0038/bin/run.sh#L38) there are certain assumptions about what the exit code should be.
* 0 is all OK
* 2 is test failures
* 1 is any other error.

Rather than have to adjust the test runner, I'll add another commit here to use those statuses.

**Comment by axtens** [comment]
I haven't read everything fully yet. Is there somewhere where you've changed from "... FAIL" to "failed" as the last bit of code I did look at had lots of `"failed" . cr` in it.

**Comment by glennj** [comment]
I have not changed the messages: "... Fail" still exists:
* https://github.com/exercism/8th/blob/55fc83ba3bb3703ad99b8bf4d020469e88eab877/exercises/practice/acronym/test-words.8th#L19
* https://github.com/exercism/8th/blob/55fc83ba3bb3703ad99b8bf4d020469e88eab877/exercises/practice/acronym/test-words.8th#L85

That "failed . cr" you saw is in the place where the summary is output: https://github.com/exercism/8th/blob/55fc83ba3bb3703ad99b8bf4d020469e88eab877/exercises/practice/acronym/test-words.8th#L88

It looks like this:
```none
$ bin/test-no-docker acronym
test-words.8th
acronym.8th
acronym-tests.8th
ignoring punctuation and casing  ... FAIL
ignores punctuation  ... OK
from phrases with acronyms  ... OK
from phrases with apostrophes  ... OK
from title case  ... OK
from lower case  ... FAIL
from a very long abbreviation  ... OK
from phrases with consecutive delimiters  ... FAIL
from phrases with underscore emphasis  ... OK
9 tests planned - 6 passed - 3 failed
```

**Comment by axtens** [comment]
Riiiight. I should read more and speak less.

**Comment by softmoth** [comment]
I think it looks good.  The changes to test-words.8th seem pretty straightforward and are an improvement in my eyes. Especially factoring out the test-passed and test-failed words.

Nice to have a stand-alone test runner; does it make sense to call that from within docker, too, so the two can't diverge (and to reduce duplication possibly)?

**Comment by glennj** [comment]
> does it make sense to call that from within docker, too, so the two can't diverge (and to reduce duplication possibly)

My first reaction is no: this script is specifically for testing the example.8th for exercise development and for CI; while the test runner is for testing user submissions.

However I will have another look at the test runner's run.sh.

**Review by axtens — APPROVED** [review]

**Comment by axtens** [comment]
Live!

**Pull request merged**
