### PR TITLE
Fix test files

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@glennj @axtens I'm not entirely sure what's going on here. If I run `bin/test` locally, it all works fine.

**Review by axtens — APPROVED** [review]

**Review by axtens — APPROVED** [review]

**Comment by axtens** [comment]
Looks good to me

**Comment by ErikSchierboom** [comment]
Yeah, but CI _is_ failing, so something is amiss.

**Review by axtens — CHANGES_REQUESTED** [review]
```
 sum-of-multiples: example solution did not pass the tests
{
  "version": 1,
  "status": "error",
  "message": "\u001b[37m\u001b[40m-1 tests planned - 0 passed - 0 skipped - 0 failed\n\u001b[31m\u001b[40m... FAIL - not all tests completed\u001b[37m\u001b[40m\nException: Unknown test-passed: at line 109 byte 2593 in libs/exercism/test <- G:eval <- I:include?: task REPL"
}
```

**Comment by ErikSchierboom** [comment]
@axtens I had noticed that, but to me it looks like the `libs/exercism/test` file _does_ have that.

**Review by glennj — APPROVED** [review]

**Pull request merged**
