### PR TITLE
sync docs and metadata

### PR DESCRIPTION
**Pull request by glennj**
No big changes, just syncing the docs and metadata with what's in problem specs.

### CODE REVIEW

**Comment by glennj** [comment]
@ErikSchierboom can you look into the CI failure?

> Error: Input required and not supplied: token

This track checks out the 8th-test-runner: https://github.com/exercism/8th/blob/8049df00db4484b74ba7df477cbee70afcc18a0b/.github/workflows/test.yml#L22

**Comment by ErikSchierboom** [comment]
@glennj https://github.com/exercism/8th/pull/112 fixes this, so a rebase should fix the PR

**Review by ErikSchierboom — APPROVED** [review]

**Comment by glennj** [comment]
> @glennj #112 fixes this, so a rebase should fix the PR

Hmm, apparently not, even with the new SHA pin: https://github.com/exercism/8th/actions/runs/7397728111/job/20125384267?pr=111

image

**Comment by ErikSchierboom** [comment]
@glennj Ah, now I know. This is running from your fork, which means it can't work :)

**Pull request merged**
