### PR TITLE
Create the Sieve of Eratosthenes exercise.

### PR DESCRIPTION
**Pull request by glennj**
I'm giving it difficulty 8, which is "hard". 

Also, a script to automate adding new exercises.

This touches the test-words.8th script, adding a new test word (compare arrays for equality, using numeric comparison for each element). To avoid a messy code review, I'll hold off copying it to all the other exercises until this exercise is ready for approval.

### CODE REVIEW

**Review by axtens — APPROVED** [review]
I expect you've run this past the mob in the forum. `a:generate` is new to me. I'm stoked that you're adding exercises.

**Comment by softmoth** [comment]
Looks good! My only thought is that the new test word has a better name, and probably `test_eqa` should become `test_array_eq_str`, and `test_eqa2` should become `test_array_eq_array_num`(?). I agree with Bruce, the solution is interesting and I don't have any suggested improvements.

**Comment by glennj** [comment]
Hmm, naming things ...

| current | perhaps ... |
| --- | --- |
| test_eq | test-num-eq |
| test_eqs | test-str-eq |
| test_true | test-true |
| test_false | test-false |
| test_null | test-null |
| test_eqa | test-arr-of-str-eq |
| test_array_eq_num | test-arr-of-num-eq |
| test_eqa2 | test-arr-of-arr-of-num-eq |
| test_map_eq | test-map-num-eq |
| test_map_neq | test-map-num-neq |

I'd be tempted to use `is-...` but dealing with skips and whatnot adds more meaning.

**Comment by axtens** [comment]
Rather than `a:generate` you could also use `loop`, viz
`a:new ( drop true a:push ) 1 1000 loop` with a bit of juggling to get your `n` into where the `1000` currently is.

**Pull request merged**
