### PR TITLE
dos2unix and turning the track on

### PR DESCRIPTION
**Pull request by axtens**
Just in case you see anything obvious @ErikSchierboom

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
What does dos2unix refer to?

**Comment by axtens** [comment]
dos2unix was used to change the lineends to LF after that got changed somehow to CRLF. What's the git command to stop lineend translation?

**Comment by ErikSchierboom** [comment]
You have to add a .gitattributes file thah specifies the correct line endings.

**Review by ErikSchierboom — APPROVED** [review]
The test runner is now working: https://github.com/exercism/8th/actions/runs/4013166412

Screenshot 2023-01-26 at 08 47 14

The reason CI fails is because you're creating a PR from a fork and we're using a secret to clone the test runner repo: https://github.com/actions/checkout/issues/298

The only thing you could do is to not submit PRs from a fork, but instead submit PRs from this repository.

I think we're good now!

**Pull request merged**
