### PR TITLE
Add check to validate the stack is the expected size

### LINKED ISSUE #133: Failing test name not printed when stack is not of expected size
When a test fails and the stack is not of the size expected by the tests, the test name is not printed.

E.g., try using this (wrong) implementation for `sieve`:

```8th
: primes \ n -- a
  [1]
;
```

```
 []  ... FAIL
    Actual:    « [1]»
    Expected:  «1»
```

However, changing it to:

```8th
: primes \ n -- a
  drop [1]
;
```

does output the test name:

```8th
no primes under two  ... FAIL
    Actual:    « [1]»
    Expected:  « []»
```

@axtens is this something you can fix?

### PR DESCRIPTION
**Pull request by glennj**
Fixes #133

### CODE REVIEW

**Comment by glennj** [comment]
If we want to promote stack hygiene, we could emit a warning about a non-empty r-stack. Worthwhile?

**Review by axtens — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
@glennj I'm not entirely sure, but I think this might have broken the test runner. I get something like this on all solutions now:

```
PANIC: expected stack depth to be 3
Stack is:

4    a: 00007f0772041c80 1   []
3    a: 00007f0772041bc0 1   []
2    s: 00007f0772321d40 1  no primes under two
1    T: 00007f07720a1220 1  false

5 tests planned - 0 passed - 0 skipped - 0 failed
... FAIL - not all tests completed
```

**Comment by glennj** [comment]
I'll look

**Comment by glennj** [comment]
Thoughts please on: https://forum.exercism.org/t/8th-checking-stack-depth-in-tests/10856

**Comment by ErikSchierboom** [comment]
The 8th test runner has been updated to the latest version: https://github.com/exercism/8th-test-runner/actions/runs/8749574686

**Pull request merged**
