### PR TITLE
Apply configlet fmt

### PR DESCRIPTION
**Pull request by ErikSchierboom**
I need to figure out why this fails CI.

### CODE REVIEW

**Comment by axtens** [comment]
Due to your desire for varargs on testing and @glennj's depth testing gone awry

**Comment by glennj** [comment]
> I need to figure out why this fails CI.

The same code passed CI in the PR: https://github.com/exercism/8th/pull/137/checks
But failed when it was merged into main: https://github.com/exercism/8th/commit/068d3be8913863fca1645eac614d7dc4e4015381

It's the same workflow for both paths: https://github.com/exercism/8th/blob/main/.github/workflows/test.yml

I can't figure out where that "false" in the stack is coming from.

**Review by glennj — APPROVED** [review]

**Comment by glennj** [comment]
I can't even test with docker locally:
```
$ bin/test
Checking acronym exercise...
Unable to find image 'exercism/8th-test-runner:latest' locally
docker: Error response from daemon: pull access denied for exercism/8th-test-runner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by ErikSchierboom** [comment]
> I can't even test with docker locally:

That's because the test runner is a private repo as it contains the `8th.zip` file which we don't to other people to distribute. If @axtens is happy with it, I could give you access to that repo.

**Comment by axtens** [comment]
Will that compromise the developer's security? Do I trust@glennj that much?

**Comment by ErikSchierboom** [comment]
That's what you need to decide

**Pull request merged**
